[package]
name = "pr-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.21.3"
paste = "1.0.15"
quote = "1.0.41"
serde_json = "1.0.145"
syn = { version = "2.0.106", features = ["full", "parsing"] }
